[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
bump_map = {"break" = "MAJOR", "new" = "MINOR", "fix" = "PATCH", "hotfix" = "PATCH"}
bump_pattern = "^(break|new|fix|hotfix)"
change_type_map = {"feature" = "Feat", "bug fix" = "Fix"}
change_type_order = ["BREAKING CHANGE", "feat", "fix", "refactor", "perf"]
changelog_pattern = "^(feature|bug fix)?(!)?"
commit_parser = "^(?P<change_type>feature|bug fix):\\s(?P<message>.*)?"
example = "feature: this feature enable customize through config file"
info = """
This is customized info
"""
info_path = "cz_customize_info.txt"
message_template = "{{change_type}}:{% if show_message %} {{message}}{% endif %}"
schema = "<type>: <body>"
schema_pattern = "(feature|bug fix):(\\s.*)"

[[tool.commitizen.customize.questions]]
choices = [
  {value = "feat", name = "feat: æ©Ÿèƒ½è¿½åŠ ", emoji = "ğŸŒŸ"},
  {value = "fix", name = "fix: ãƒã‚°ã®ä¿®æ­£", emoji = "ğŸ”§"},
  {value = "docs", name = "docs: ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆã®ã¿ã®å¤‰æ›´", emoji = "ğŸ—’"},
  {value = "style", name = "style: ã‚³ãƒ¼ãƒ‰ã®å‹•ä½œã«å½±éŸ¿ã—ãªã„ã€è¦‹ãŸç›®ã ã‘ã®å¤‰æ›´ï¼ˆã‚¹ãƒšãƒ¼ã‚¹ã€ãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆã€æ¬ è½ã®ä¿®æ­£ã€ã‚»ãƒŸã‚³ãƒ­ãƒ³ãªã©)", emoji = "ğŸ¨"},
  {value = "refactor", name = "refactor: ãƒã‚°ã®ä¿®æ­£ã‚„æ©Ÿèƒ½ã®è¿½åŠ ã§ã¯ãªã„ã‚³ãƒ¼ãƒ‰ã®å¤‰æ›´", emoji = "â™»ï¸"},
  {value = "perf", name = "perf: ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã‚’å‘ä¸Šã•ã›ã‚‹ã‚³ãƒ¼ãƒ‰ã®å¤‰æ›´", emoji = "â«"},
  {value = "test", name = "test: ä¸è¶³ã—ã¦ã„ã‚‹ãƒ†ã‚¹ãƒˆã®è¿½åŠ ã‚„æ—¢å­˜ã®ãƒ†ã‚¹ãƒˆã®ä¿®æ­£", emoji = "ğŸ§ª"},
  {value = "chore", name = "chore: ãƒ“ãƒ«ãƒ‰ãƒ—ãƒ­ã‚»ã‚¹ã‚„ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆç”Ÿæˆãªã©ã®è£œåŠ©ãƒ„ãƒ¼ãƒ«ã‚„ãƒ©ã‚¤ãƒ–ãƒ©ãƒªã®å¤‰æ›´", emoji = "ğŸ§"},
]
name = "change_type"
type = "list"
# choices = ["feature", "fix"]  # short version
message = "ã‚³ãƒŸãƒƒãƒˆã™ã‚‹ã‚¿ã‚¤ãƒ—ã‚’é¸æŠã—ã¦ãã ã•ã„"

[[tool.commitizen.customize.questions]]
message = "ã‚³ãƒŸãƒƒãƒˆå†…å®¹ã«ã¤ã„ã¦å…¥åŠ›ã—ã¦ãã ã•ã„:"
name = "message"
type = "input"

[[tool.commitizen.customize.questions]]
message = "Do you want to add body message in commit?"
name = "show_message"
type = "confirm"
